services:
  db:
    image: postgres:16-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: fundarbok
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - fundarbok_dev_data:/var/lib/postgresql/data

volumes:
  fundarbok_dev_data:
